# -----------------------
# STAGE 1 : BUILD ANGULAR
# -----------------------
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build -- --configuration production

# -----------------------
# STAGE 2 : SERVE WITH NGINX
# -----------------------
FROM nginx:alpine

COPY --from=build /app/dist/* /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
